2024-12-03 12:26:42,882 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 12:26:42,891 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 12:26:44,478 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 12:26:44,485 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 12:26:44,661 - FlaskAppLogger - ERROR - Error saving data to database: name 'user_name' is not defined
2024-12-03 12:26:54,301 - FlaskAppLogger - ERROR - Error saving data to database: name 'user_name' is not defined
2024-12-03 12:27:12,181 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 12:27:12,187 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 12:27:16,505 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 12:27:16,512 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 12:27:36,477 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 12:27:36,480 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 12:27:38,033 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 12:27:38,042 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 12:27:43,335 - FlaskAppLogger - INFO - Recieved data: None
2024-12-03 12:27:43,335 - FlaskAppLogger - ERROR - Error saving data to database: argument of type 'NoneType' is not iterable
2024-12-03 12:40:50,541 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 12:40:50,545 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 12:40:52,126 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 12:40:52,131 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 12:40:55,633 - FlaskAppLogger - INFO - Recieved data: None
2024-12-03 12:40:55,634 - FlaskAppLogger - ERROR - Error saving data to database: argument of type 'NoneType' is not iterable
2024-12-03 12:41:18,214 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 12:41:18,222 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 12:41:21,346 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 12:41:21,353 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 12:41:23,061 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 12:41:23,990 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1009, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 320, 'wind_speed': 3.09}
2024-12-03 12:42:20,058 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 12:42:20,954 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1009, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 320, 'wind_speed': 3.09}
2024-12-03 12:42:46,383 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 12:42:46,389 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 12:42:56,550 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 12:42:56,553 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 12:42:58,007 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 12:42:58,014 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 12:42:59,968 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 12:43:00,870 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1009, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 320, 'wind_speed': 3.09}
2024-12-03 12:44:00,106 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 12:44:00,112 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 12:44:02,788 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 12:44:03,797 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1009, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 320, 'wind_speed': 3.09}
2024-12-03 12:44:14,741 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 12:44:15,715 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1009, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 320, 'wind_speed': 3.09}
2024-12-03 12:44:33,729 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 12:44:33,736 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 12:44:35,031 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 12:44:35,957 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1009, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 320, 'wind_speed': 3.09}
2024-12-03 12:45:47,912 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 12:45:47,916 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 12:45:49,412 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 12:45:49,421 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 12:45:50,374 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 12:45:51,282 - FlaskAppLogger - ERROR - Error saving data to database: name 'user_name' is not defined
2024-12-03 12:46:33,930 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 12:46:34,880 - FlaskAppLogger - ERROR - Error saving data to database: name 'user_name' is not defined
2024-12-03 12:52:26,984 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-03 12:52:44,515 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 12:52:45,444 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1009, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 320, 'wind_speed': 3.09}
2024-12-03 12:53:04,241 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 12:53:05,213 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1009, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 320, 'wind_speed': 3.09}
2024-12-03 12:53:09,714 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 12:53:10,642 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1009, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 320, 'wind_speed': 3.09}
2024-12-03 12:53:13,891 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 12:53:14,838 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1009, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 320, 'wind_speed': 3.09}
2024-12-03 12:57:01,875 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 12:57:01,879 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 12:57:03,297 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 12:57:03,303 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 12:57:10,883 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-03 13:06:43,409 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:11:11,070 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:11:12,025 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:11:33,848 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:11:34,741 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:11:47,690 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:11:49,474 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:11:50,341 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:22:24,218 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 13:22:24,222 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 13:22:25,710 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 13:22:25,723 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 13:22:29,077 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-03 13:22:32,268 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:22:33,236 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:22:33,427 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:22:34,393 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:22:35,994 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:22:36,874 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:23:01,764 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:23:02,676 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:23:02,740 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:23:03,628 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:23:03,640 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:23:04,736 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:24:12,000 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:24:12,916 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:24:12,932 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:24:13,829 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:24:13,844 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:24:14,714 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:24:14,727 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:24:15,628 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:24:15,643 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:24:16,512 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:24:16,532 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:24:17,386 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:24:17,405 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:24:18,272 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:24:18,295 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:24:19,145 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:24:19,160 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:24:20,039 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:24:20,051 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:24:20,919 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:24:20,933 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:24:21,912 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:24:21,926 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:24:22,837 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:24:22,851 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:24:23,718 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:24:23,740 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:24:24,938 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:24:57,784 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:24:58,787 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:26:30,256 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:26:31,187 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:27:33,675 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:27:34,594 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:27:34,836 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:27:35,763 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:27:35,775 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:27:36,683 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:27:36,696 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:27:37,714 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:29:02,827 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:29:03,718 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:29:21,588 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:29:22,488 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:29:26,596 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:29:27,476 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:33:07,925 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:33:08,968 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:35:20,956 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:35:21,884 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:36:20,473 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:36:21,487 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:37:17,189 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:37:18,127 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:37:40,800 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:37:41,682 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:37:50,155 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:37:51,082 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:37:54,237 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:37:55,196 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:38:09,251 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:38:10,164 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:38:11,963 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:38:12,803 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:38:21,227 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:38:22,173 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:38:26,180 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:38:27,042 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:38:34,996 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:38:35,886 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:38:40,835 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:38:41,810 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:38:44,556 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:38:45,451 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:39:17,019 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:39:18,002 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:39:24,951 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:39:25,843 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:39:28,542 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:39:29,518 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 13:47:31,890 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 13:47:31,892 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 13:47:33,312 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 13:47:33,317 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 13:47:40,883 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-03 13:47:45,313 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-03 13:47:55,200 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai, Maharashtra, India
2024-12-03 13:48:02,468 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai, Maharashtra, India
2024-12-03 13:48:06,660 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:48:07,573 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:48:08,454 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:48:09,340 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:48:16,632 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai, Maharashtra, India
2024-12-03 13:48:27,052 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:48:29,821 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:48:30,811 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1008, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 290, 'wind_speed': 3.6}
2024-12-03 13:48:38,618 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:48:39,541 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 62, 'pressure': 1008, 'temp': 29.99, 'weather_condition': 'Smoke', 'wind_degree': 280, 'wind_speed': 4.12}
2024-12-03 13:49:01,365 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 13:49:13,594 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 16:14:44,357 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 16:14:52,094 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-03 16:14:58,167 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 16:15:25,752 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-03 16:15:26,030 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-03 16:15:27,127 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Delhi', 'country_name': 'IN', 'humidity': 36, 'pressure': 1013, 'temp': 26.05, 'weather_condition': 'Haze', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 16:15:33,166 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-03 16:31:10,908 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 16:31:12,913 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 16:31:14,914 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 16:31:16,906 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 16:31:18,909 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 16:31:20,905 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 16:31:22,911 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 16:31:24,905 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 16:31:26,906 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 16:31:28,917 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 16:31:30,916 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 16:31:32,915 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 16:31:34,917 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 16:31:36,909 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 16:31:39,903 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-03 16:31:41,904 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-03 16:31:43,900 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-03 16:31:44,336 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-03 16:31:45,362 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Delhi', 'country_name': 'IN', 'humidity': 36, 'pressure': 1013, 'temp': 26.05, 'weather_condition': 'Haze', 'wind_degree': 280, 'wind_speed': 3.09}
2024-12-03 16:31:45,901 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-03 16:31:47,894 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-03 16:31:49,903 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-03 16:31:51,903 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-03 16:31:53,905 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-03 16:31:55,908 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-03 16:31:57,907 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-03 16:31:59,900 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-03 16:32:02,193 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-03 16:32:04,184 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-03 16:32:06,185 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-03 16:32:08,182 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-03 16:32:10,190 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-03 16:32:12,189 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-03 16:32:14,180 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-03 16:32:16,195 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-03 16:32:18,187 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-03 16:32:20,181 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-03 16:32:22,193 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-03 16:32:24,185 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-03 16:32:26,191 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-03 16:32:28,195 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-03 16:32:30,182 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-03 16:32:32,183 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-03 16:32:34,194 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-03 16:32:36,201 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-03 16:32:38,180 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-03 16:32:40,190 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-03 16:32:42,260 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-03 16:32:44,191 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-03 16:32:46,183 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-03 16:32:47,904 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-03 16:32:53,477 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 16:32:55,476 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 16:32:57,478 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 16:32:59,481 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 16:33:01,476 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 16:33:03,476 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 16:33:05,476 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 16:33:07,475 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 16:33:09,477 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 16:33:28,989 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 16:33:30,980 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 16:33:32,983 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 16:34:13,288 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 16:34:15,283 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 16:34:17,289 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 16:34:20,191 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 16:34:22,186 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 16:34:24,183 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 16:34:25,364 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 16:34:31,371 - FlaskAppLogger - INFO - Fetching weather data for city: London
2024-12-03 16:34:33,372 - FlaskAppLogger - INFO - Fetching weather data for city: London
2024-12-03 16:34:35,369 - FlaskAppLogger - INFO - Fetching weather data for city: London
2024-12-03 16:34:37,366 - FlaskAppLogger - INFO - Fetching weather data for city: London
2024-12-03 16:34:39,376 - FlaskAppLogger - INFO - Fetching weather data for city: London
2024-12-03 16:34:41,367 - FlaskAppLogger - INFO - Fetching weather data for city: London
2024-12-03 16:37:49,246 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 16:37:49,249 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 16:37:50,735 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 16:37:50,741 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 16:37:52,559 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-03 16:39:20,724 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 16:39:20,729 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 16:39:22,300 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 16:39:22,305 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 16:39:23,550 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-03 16:47:18,487 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 16:47:18,494 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 16:47:22,490 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 16:47:22,501 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 17:20:39,030 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 17:20:39,034 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 17:20:40,554 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 17:20:40,561 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 17:20:43,107 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-03 17:50:45,808 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 17:50:45,816 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 17:50:51,793 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-03 17:52:12,150 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 17:52:12,158 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 17:52:17,269 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 17:52:17,276 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 17:52:26,088 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-03 17:52:26,333 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-03 18:06:43,398 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 18:06:43,408 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 18:06:46,568 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-03 18:20:30,268 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 18:20:30,273 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 18:20:48,840 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 18:20:48,846 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 18:21:18,630 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 18:21:18,636 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 18:21:26,574 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 18:21:26,587 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 18:21:31,649 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 18:21:31,655 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 18:23:04,254 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 18:23:04,260 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 18:23:08,323 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 18:23:08,330 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 18:23:14,113 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-03 18:25:18,658 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 18:25:18,663 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 18:25:31,480 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 18:25:31,488 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 18:25:33,537 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 18:25:33,543 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 18:25:37,298 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-03 18:26:34,403 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 18:26:34,409 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 18:26:40,916 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 18:26:40,922 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 18:27:53,295 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 18:27:53,301 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 18:27:56,434 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 18:27:56,442 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 18:27:56,706 - FlaskAppLogger - WARNING - Unauthorized deletion attempt for log id: 66 by user: None
2024-12-03 18:28:01,655 - FlaskAppLogger - WARNING - Unauthorized deletion attempt for log id: 66 by user: None
2024-12-03 18:28:08,153 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-03 18:28:08,357 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-03 18:28:11,844 - FlaskAppLogger - ERROR - Error deleting log: 65, Exception: Object '<WeatherData at 0x1da41596d20>' is already attached to session '4' (this is '5')
2024-12-03 18:28:15,186 - FlaskAppLogger - ERROR - Error deleting log: 67, Exception: Object '<WeatherData at 0x1da4157dc40>' is already attached to session '6' (this is '7')
2024-12-03 18:28:16,453 - FlaskAppLogger - ERROR - Error deleting log: 66, Exception: Object '<WeatherData at 0x1da415c8bf0>' is already attached to session '8' (this is '9')
2024-12-03 18:29:14,802 - FlaskAppLogger - WARNING - Unauthorized deletion attempt for log id: 66 by user: None
2024-12-03 18:29:15,862 - FlaskAppLogger - WARNING - Unauthorized deletion attempt for log id: 66 by user: None
2024-12-03 18:29:16,630 - FlaskAppLogger - WARNING - Unauthorized deletion attempt for log id: 66 by user: None
2024-12-03 18:29:17,567 - FlaskAppLogger - WARNING - Unauthorized deletion attempt for log id: 66 by user: None
2024-12-03 18:29:18,200 - FlaskAppLogger - WARNING - Unauthorized deletion attempt for log id: 66 by user: None
2024-12-03 18:30:40,437 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 18:30:40,443 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 18:30:46,035 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 18:30:46,044 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 18:30:51,826 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 18:30:51,831 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 18:30:54,649 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 18:30:54,655 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 18:31:00,373 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 18:31:00,381 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 18:31:03,980 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 18:31:03,986 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 18:31:07,091 - FlaskAppLogger - WARNING - Unauthorized deletion attempt for log id: 66 by user: None
2024-12-03 18:31:08,721 - FlaskAppLogger - WARNING - Unauthorized deletion attempt for log id: 66 by user: None
2024-12-03 18:31:22,950 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 18:31:22,957 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 18:31:52,466 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 18:31:52,469 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 18:31:54,073 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 18:31:54,078 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 18:32:29,136 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 18:32:29,144 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 18:32:45,737 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-03 18:32:51,445 - FlaskAppLogger - ERROR - Error deleting log: 66, Exception: Object '<WeatherData at 0x2f39966e4b0>' is already attached to session '4' (this is '5')
2024-12-03 18:33:45,063 - FlaskAppLogger - ERROR - Error deleting log: 66, Exception: Object '<WeatherData at 0x2f39a37b770>' is already attached to session '10' (this is '11')
2024-12-03 18:33:52,020 - FlaskAppLogger - ERROR - Error deleting log: 68, Exception: Object '<WeatherData at 0x2f39a42ede0>' is already attached to session '12' (this is '13')
2024-12-03 18:33:53,005 - FlaskAppLogger - ERROR - Error deleting log: 68, Exception: Object '<WeatherData at 0x2f39a3ea840>' is already attached to session '14' (this is '15')
2024-12-03 18:34:10,131 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 18:34:10,137 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 18:34:25,873 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 18:34:25,880 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 18:34:29,771 - FlaskAppLogger - ERROR - Error deleting log: 68, Exception: Object '<WeatherData at 0x1fd8eadc140>' is already attached to session '1' (this is '2')
2024-12-03 18:34:31,535 - FlaskAppLogger - ERROR - Error deleting log: 68, Exception: Object '<WeatherData at 0x1fd8bdec3b0>' is already attached to session '3' (this is '4')
2024-12-03 18:35:09,005 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-03 18:36:01,881 - FlaskAppLogger - ERROR - Error deleting log: 67, Exception: Object '<WeatherData at 0x1fd8eb2daf0>' is already attached to session '7' (this is '8')
2024-12-03 18:36:03,482 - FlaskAppLogger - ERROR - Error deleting log: 67, Exception: Object '<WeatherData at 0x1fd8eb08da0>' is already attached to session '9' (this is '10')
2024-12-03 18:36:04,398 - FlaskAppLogger - ERROR - Error deleting log: 67, Exception: Object '<WeatherData at 0x1fd8eb0b6b0>' is already attached to session '11' (this is '12')
2024-12-03 18:36:13,381 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 18:36:13,387 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 18:36:16,843 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 18:36:16,860 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 18:36:21,496 - FlaskAppLogger - ERROR - Error deleting log: 67, Exception: Object '<WeatherData at 0x14b5b92fd10>' is already attached to session '1' (this is '2')
2024-12-03 18:36:22,686 - FlaskAppLogger - ERROR - Error deleting log: 67, Exception: Object '<WeatherData at 0x14b5b960ce0>' is already attached to session '3' (this is '4')
2024-12-03 18:36:23,684 - FlaskAppLogger - ERROR - Error deleting log: 67, Exception: Object '<WeatherData at 0x14b5b9606e0>' is already attached to session '5' (this is '6')
2024-12-03 18:36:29,530 - FlaskAppLogger - ERROR - Error deleting log: 68, Exception: Object '<WeatherData at 0x14b5b961a60>' is already attached to session '7' (this is '8')
2024-12-03 18:59:18,608 - FlaskAppLogger - ERROR - Error deleting log: 68, Exception: Object '<WeatherData at 0x14b5b9626c0>' is already attached to session '9' (this is '10')
2024-12-03 18:59:21,748 - FlaskAppLogger - ERROR - Error deleting log: 68, Exception: Object '<WeatherData at 0x14b5b961910>' is already attached to session '11' (this is '12')
2024-12-03 18:59:22,581 - FlaskAppLogger - ERROR - Error deleting log: 68, Exception: Object '<WeatherData at 0x14b5b963d40>' is already attached to session '13' (this is '14')
2024-12-03 18:59:26,870 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-03 19:00:17,385 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 19:00:17,391 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 19:00:21,248 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 19:00:21,256 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 19:02:07,706 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-03 19:10:01,292 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 19:10:01,300 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 19:10:06,588 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-03 19:16:17,490 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 19:16:17,495 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 19:16:21,740 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 19:16:21,746 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 19:16:23,489 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-03 19:17:44,695 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 19:17:44,702 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 19:17:49,349 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-03 19:19:54,733 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 19:19:54,739 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 19:21:24,107 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-03 19:21:40,533 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 19:21:40,552 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 19:22:10,523 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-03 19:24:21,336 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 19:24:21,339 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 19:24:22,951 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 19:24:22,957 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 19:24:45,692 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 19:24:45,697 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 19:27:10,645 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 19:27:10,650 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 19:27:24,120 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 19:27:24,126 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 19:27:33,661 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-03 19:46:09,099 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 19:46:09,106 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 19:47:10,421 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 19:47:10,430 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 19:47:13,927 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 19:47:13,940 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 19:47:17,082 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 19:47:17,088 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 19:47:22,329 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 19:47:22,335 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 19:48:02,521 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 19:48:02,527 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 19:48:05,065 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-03 19:59:42,171 - FlaskAppLogger - INFO - User Anmol deleted weather log with id: 65
2024-12-03 20:00:00,056 - FlaskAppLogger - INFO - User Anmol deleted weather log with id: 66
2024-12-03 20:00:01,020 - FlaskAppLogger - INFO - User Anmol deleted weather log with id: 67
2024-12-03 20:00:01,963 - FlaskAppLogger - INFO - User Anmol deleted weather log with id: 68
2024-12-03 20:00:37,633 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 20:00:37,639 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 20:00:41,082 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-03 20:00:43,996 - FlaskAppLogger - INFO - User Anmol deleted weather log with id: 65
2024-12-03 20:00:47,228 - FlaskAppLogger - INFO - User Anmol deleted weather log with id: 67
2024-12-03 20:00:49,252 - FlaskAppLogger - INFO - User Anmol deleted weather log with id: 68
2024-12-03 20:01:59,074 - FlaskAppLogger - INFO - User Anmol deleted weather log with id: 66
2024-12-03 20:03:07,416 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 20:03:07,424 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 20:03:09,961 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-03 20:03:13,299 - FlaskAppLogger - INFO - User Anmol deleted weather log with id: 65
2024-12-03 20:03:33,966 - FlaskAppLogger - INFO - User Anmol deleted weather log with id: 67
2024-12-03 20:04:55,980 - FlaskAppLogger - INFO - User Anmol deleted weather log with id: 68
2024-12-03 20:05:09,783 - FlaskAppLogger - INFO - User Anmol deleted weather log with id: 66
2024-12-03 20:05:19,093 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 20:05:19,096 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 20:05:20,566 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 20:05:20,572 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 20:05:24,556 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-03 20:05:29,075 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-03 20:05:31,306 - FlaskAppLogger - INFO - User Anmol deleted weather log with id: 65
2024-12-03 20:09:54,578 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 20:10:00,481 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 20:10:06,349 - FlaskAppLogger - INFO - Error thrown successfully.
