2024-12-04 23:52:40,245 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 23:52:40,252 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 23:52:41,880 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 23:52:41,887 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 23:52:52,048 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-04 23:57:00,520 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 23:57:00,524 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 23:57:01,974 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 23:57:01,980 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 00:05:38,729 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 00:05:38,732 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 00:05:40,155 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 00:05:40,160 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 00:07:33,407 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-05 00:12:20,512 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-05 00:12:23,458 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-05 00:12:25,456 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-05 00:12:27,465 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-05 00:12:51,216 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-05 00:12:53,214 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-05 00:12:55,593 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-05 00:13:01,266 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-05 00:13:03,269 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-05 00:13:05,265 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-05 00:13:07,271 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-05 00:13:09,268 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-05 00:13:11,268 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-05 00:13:13,267 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-05 00:13:15,669 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-05 00:13:17,274 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-05 00:23:58,886 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 00:23:58,891 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 00:24:00,362 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 00:24:00,368 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 00:24:09,832 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-05 00:24:13,327 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-05 00:24:14,284 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 65, 'pressure': 1010, 'temp': 28.99, 'weather_condition': 'Haze', 'wind_degree': 0, 'wind_speed': 0}
2024-12-05 00:24:29,045 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-05 00:24:29,964 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 65, 'pressure': 1010, 'temp': 28.99, 'weather_condition': 'Haze', 'wind_degree': 0, 'wind_speed': 0}
2024-12-05 00:24:39,210 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 00:24:39,214 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 00:24:40,782 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 00:24:40,787 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 00:24:41,836 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-05 00:25:05,077 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-05 00:25:06,038 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 65, 'pressure': 1010, 'temp': 28.99, 'weather_condition': 'Haze', 'wind_degree': 0, 'wind_speed': 0}
2024-12-05 09:51:28,912 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 09:51:28,919 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 09:53:14,553 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 09:53:14,561 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 10:00:56,877 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 10:00:56,881 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 10:00:58,552 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 10:00:58,558 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 10:01:12,684 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-05 10:01:33,874 - FlaskAppLogger - INFO - Registration attempt for user: nitkarsh.chourasia@yahoo.com
2024-12-05 10:01:33,880 - FlaskAppLogger - WARNING - Invalid username: nitkarsh.chourasia@yahoo.com
2024-12-05 10:01:53,737 - FlaskAppLogger - INFO - Registration attempt for user: nitkarsh.chourasia@yahoo.com
2024-12-05 10:01:53,739 - FlaskAppLogger - WARNING - Invalid username: nitkarsh.chourasia@yahoo.com
2024-12-05 10:01:53,780 - FlaskAppLogger - INFO - Registration attempt for user: nitkarsh.chourasia@yahoo.com
2024-12-05 10:01:53,783 - FlaskAppLogger - WARNING - Invalid username: nitkarsh.chourasia@yahoo.com
2024-12-05 10:09:30,578 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 10:09:30,585 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 10:09:34,936 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 10:09:34,942 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 10:09:38,485 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 10:09:38,492 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 10:09:43,037 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 10:09:43,042 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 10:09:51,825 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 10:09:51,839 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 10:09:57,710 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 10:09:57,726 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 10:10:00,861 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 10:10:00,867 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 10:10:06,411 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 10:10:06,560 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 10:10:12,567 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 10:10:12,573 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 10:10:30,429 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 10:10:30,437 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 10:13:10,817 - FlaskAppLogger - INFO - Registration attempt for user: sfdsfdsaf@@@
2024-12-05 10:13:10,828 - FlaskAppLogger - WARNING - Invalid username: sfdsfdsaf@@@
2024-12-05 10:13:42,668 - FlaskAppLogger - INFO - Registration attempt for user: how_are_you
2024-12-05 10:13:42,672 - FlaskAppLogger - WARNING - Weak password attempt during registration for user: how_are_you
2024-12-05 10:13:42,710 - FlaskAppLogger - INFO - Registration attempt for user: how_are_you
2024-12-05 10:13:42,713 - FlaskAppLogger - WARNING - Weak password attempt during registration for user: how_are_you
2024-12-05 10:14:07,105 - FlaskAppLogger - INFO - Registration attempt for user: admin
2024-12-05 10:14:07,437 - FlaskAppLogger - INFO - User registered successfully: admin
2024-12-05 10:14:26,378 - FlaskAppLogger - INFO - Login attempt for user: admin
2024-12-05 10:14:26,407 - FlaskAppLogger - INFO - Login attempt for user: admin
2024-12-05 10:14:32,903 - FlaskAppLogger - INFO - User admin logged out.
2024-12-05 10:14:44,722 - FlaskAppLogger - INFO - Registration attempt for user: jghfjghjghfj@@
2024-12-05 10:14:44,737 - FlaskAppLogger - WARNING - Invalid username: jghfjghjghfj@@
2024-12-05 10:15:14,665 - FlaskAppLogger - INFO - Registration attempt for user: jghfjghjghfj@@
2024-12-05 10:15:14,668 - FlaskAppLogger - WARNING - Invalid username: jghfjghjghfj@@
2024-12-05 10:15:42,891 - FlaskAppLogger - INFO - Registration attempt for user: jghfjghjghfj@@
2024-12-05 10:15:42,893 - FlaskAppLogger - WARNING - Invalid username: jghfjghjghfj@@
2024-12-05 10:16:10,332 - FlaskAppLogger - INFO - Registration attempt for user: jghfjghjghfj@@
2024-12-05 10:16:10,333 - FlaskAppLogger - WARNING - Invalid username: jghfjghjghfj@@
2024-12-05 10:16:15,713 - FlaskAppLogger - INFO - Registration attempt for user: jghfjghjghfj@@
2024-12-05 10:16:15,715 - FlaskAppLogger - WARNING - Invalid username: jghfjghjghfj@@
2024-12-05 10:17:16,802 - FlaskAppLogger - INFO - Registration attempt for user: jghfjghjghfj@@
2024-12-05 10:17:16,804 - FlaskAppLogger - WARNING - Invalid username: jghfjghjghfj@@
2024-12-05 10:17:19,488 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 10:17:19,497 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 10:18:05,082 - FlaskAppLogger - INFO - Registration attempt for user: jghfjghjghfj@@
2024-12-05 10:18:05,084 - FlaskAppLogger - WARNING - Invalid username: jghfjghjghfj@@
2024-12-05 10:19:05,594 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 10:19:05,602 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 10:22:23,973 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 10:22:23,979 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 10:22:25,422 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 10:22:25,427 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 10:22:56,766 - FlaskAppLogger - INFO - Registration attempt for user: sdfsdafsda
2024-12-05 10:22:56,768 - FlaskAppLogger - WARNING - Passwords do not match for user: sdfsdafsda
2024-12-05 10:23:30,352 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 10:23:30,367 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 10:23:33,864 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 10:23:33,885 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 10:23:37,049 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 10:23:37,055 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 10:23:40,098 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 10:23:40,104 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 10:24:05,921 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 10:24:05,927 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 10:24:11,408 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 10:24:11,414 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 10:24:20,396 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 10:24:20,403 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 10:24:24,358 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 10:24:24,363 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 10:24:28,368 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 10:24:28,374 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 10:33:06,842 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 10:33:06,848 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 10:37:29,267 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 10:37:29,270 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 10:37:31,025 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 10:37:31,031 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 10:38:17,376 - FlaskAppLogger - INFO - Registration attempt for user: sdfasdfasdf
2024-12-05 10:38:17,378 - FlaskAppLogger - WARNING - Passwords do not match for user: sdfasdfasdf
2024-12-05 10:38:17,393 - FlaskAppLogger - WARNING - Bad request: Passwords do not match. Please try again.
2024-12-05 11:39:37,736 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 11:39:37,740 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 11:39:39,491 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 11:39:39,498 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 11:44:10,366 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 11:44:10,372 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 11:44:17,965 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 11:44:17,970 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 11:50:31,105 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 11:50:31,108 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 11:50:32,827 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 11:50:32,833 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 11:50:53,184 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-05 11:50:53,479 - FlaskAppLogger - WARNING - Failed login attempt for user: Nitkarsh
2024-12-05 11:50:55,736 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 11:50:55,743 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 11:52:15,430 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 11:52:15,435 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 11:52:16,933 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 11:52:16,939 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 11:52:35,622 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-05 11:52:35,920 - FlaskAppLogger - WARNING - Failed login attempt for user: Nitkarsh
2024-12-05 11:54:44,572 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 11:54:44,577 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 11:55:26,812 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 11:55:26,818 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 11:55:33,200 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 11:55:33,206 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 11:55:40,972 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-05 11:55:45,068 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-05 11:55:45,383 - FlaskAppLogger - WARNING - Failed login attempt for user: Nitkarsh
2024-12-05 11:57:38,614 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 11:57:38,619 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 11:57:40,112 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 11:57:40,119 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 11:57:49,843 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-05 11:57:50,136 - FlaskAppLogger - WARNING - Failed login attempt for user: Nitkarsh
2024-12-05 11:58:47,608 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 11:58:47,614 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 11:59:12,556 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 11:59:12,561 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 11:59:18,110 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 11:59:18,116 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 11:59:22,089 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 11:59:22,097 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 11:59:29,441 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 11:59:29,447 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 11:59:33,588 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 11:59:33,593 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 11:59:36,985 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 11:59:36,995 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 11:59:39,550 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-05 11:59:39,853 - FlaskAppLogger - WARNING - Failed login attempt for user: Nitkarsh
2024-12-05 11:59:39,856 - FlaskAppLogger - WARNING - Bad request: Invalid credentials! Enter correct username and password.
2024-12-05 11:59:42,117 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 11:59:42,122 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 11:59:46,081 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-05 11:59:46,384 - FlaskAppLogger - WARNING - Failed login attempt for user: Nitkarsh
2024-12-05 11:59:46,386 - FlaskAppLogger - WARNING - Bad request: Invalid credentials! Enter correct username and password.
2024-12-05 12:01:04,664 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-05 12:01:04,969 - FlaskAppLogger - WARNING - Failed login attempt for user: Nitkarsh
2024-12-05 12:01:04,971 - FlaskAppLogger - WARNING - Bad request: Invalid credentials! Enter correct username and password.
2024-12-05 12:04:16,389 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-05 12:04:16,715 - FlaskAppLogger - WARNING - Failed login attempt for user: Nitkarsh
2024-12-05 12:04:16,717 - FlaskAppLogger - WARNING - Bad request: Invalid credentials! Enter correct username and password.
2024-12-05 12:04:45,206 - FlaskAppLogger - INFO - Registration attempt for user: @@@@fsf
2024-12-05 12:04:45,207 - FlaskAppLogger - WARNING - Invalid username: @@@@fsf
2024-12-05 12:05:01,313 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 12:05:01,318 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 12:05:04,594 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 12:05:04,599 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 12:05:19,369 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 12:05:19,373 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 12:05:20,851 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 12:05:20,859 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 12:05:48,629 - FlaskAppLogger - INFO - Registration attempt for user: sfsfsdfas@
2024-12-05 12:05:48,634 - FlaskAppLogger - WARNING - Invalid username: sfsfsdfas@
2024-12-05 12:05:48,659 - FlaskAppLogger - WARNING - Bad request: Invalid username. Please use only alphanumeric characters and underscores.
2024-12-05 12:13:15,518 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 12:13:15,523 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 12:13:16,990 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 12:13:16,998 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 12:14:48,015 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 12:14:48,023 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 12:14:49,497 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 12:14:49,504 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 12:15:52,887 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-05 12:23:09,186 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-05 12:23:11,188 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-05 12:23:13,183 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-05 12:23:15,184 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-05 12:23:17,184 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-05 13:07:29,158 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 13:07:29,164 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 13:07:33,951 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 13:07:33,974 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 13:09:20,708 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-05 13:10:30,068 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 13:10:30,074 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 13:11:07,690 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-05 13:11:10,905 - FlaskAppLogger - INFO - User Nitkarsh logged out.
2024-12-05 13:11:12,046 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-05 13:11:14,760 - FlaskAppLogger - INFO - User Nitkarsh logged out.
2024-12-05 13:11:15,781 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-05 13:11:39,549 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 13:11:39,556 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 13:11:50,743 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-05 13:12:11,557 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 13:12:11,563 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 13:13:43,851 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 13:13:43,854 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 13:13:45,678 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 13:13:45,684 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 13:14:13,188 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 13:14:13,197 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 13:14:55,781 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 13:14:55,784 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 13:14:57,299 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 13:14:57,307 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 13:15:01,692 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-05 13:15:51,290 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 13:15:51,292 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 13:15:52,752 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 13:15:52,759 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 13:15:56,389 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-05 13:17:31,618 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 13:17:31,621 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 13:17:33,103 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 13:17:33,109 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 13:17:35,581 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-05 13:18:18,719 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 13:18:18,725 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 13:18:20,068 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-05 13:21:42,157 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 13:21:42,161 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 13:21:43,645 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 13:21:43,650 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 13:21:46,837 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-05 13:23:31,133 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 13:23:31,136 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 13:23:32,607 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 13:23:32,612 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 13:26:00,712 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 13:26:00,718 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 13:26:34,417 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 13:26:34,427 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 13:26:35,909 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 13:26:35,915 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 13:27:05,400 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 13:27:05,405 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 13:27:09,608 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 13:27:09,615 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 13:27:11,190 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-05 13:27:34,637 - FlaskAppLogger - INFO - User Nitkarsh logged out.
2024-12-05 13:27:35,657 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-05 13:28:41,535 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 13:28:41,538 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 13:28:43,065 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 13:28:43,072 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 13:28:50,387 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-05 13:49:07,653 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 13:49:07,656 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 13:49:09,127 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 13:49:09,136 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 13:49:20,337 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-05 13:49:27,077 - FlaskAppLogger - INFO - User Nitkarsh logged out.
2024-12-05 13:49:28,195 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-05 13:56:02,899 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 13:56:02,902 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 13:56:04,440 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 13:56:04,446 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 13:56:05,920 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-05 13:58:16,153 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 13:58:16,158 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 13:58:28,722 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-05 14:00:47,795 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 14:00:47,798 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 14:00:49,358 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 14:00:49,364 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 14:00:50,936 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-05 14:03:02,756 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 14:03:02,759 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 14:03:04,200 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 14:03:04,207 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 14:21:41,524 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-05 15:09:26,688 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 15:09:26,692 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 15:09:28,157 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 15:09:28,162 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 15:09:29,927 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-05 15:15:16,825 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 15:15:16,829 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 15:15:18,335 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 15:15:18,340 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 15:15:20,815 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-05 15:22:52,525 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 15:22:52,530 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 15:22:54,050 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 15:22:54,056 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 15:22:55,618 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-05 15:30:24,824 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 15:30:24,832 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 15:30:26,444 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 15:30:26,450 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 15:30:27,923 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-05 15:33:35,079 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 15:33:35,083 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 15:33:36,502 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-05 15:33:36,509 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-05 15:33:38,046 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-05 15:45:16,904 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-05 15:45:17,213 - FlaskAppLogger - WARNING - Failed login attempt for user: Nitkarsh
2024-12-05 15:45:17,218 - FlaskAppLogger - WARNING - Bad request: Invalid credentials! Enter correct username and password.
2024-12-05 15:45:35,478 - FlaskAppLogger - INFO - Registration attempt for user: dsfasdf@
2024-12-05 15:45:35,482 - FlaskAppLogger - WARNING - Invalid username: dsfasdf@
2024-12-05 15:45:35,491 - FlaskAppLogger - WARNING - Bad request: Invalid username. Please use only alphanumeric characters and underscores.
2024-12-05 15:45:40,785 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-05 15:45:50,160 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-05 15:45:54,985 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-05 15:45:56,988 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-05 15:45:57,884 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 66, 'pressure': 1009, 'temp': 30.99, 'weather_condition': 'Haze', 'wind_degree': 270, 'wind_speed': 4.12}
2024-12-05 15:45:58,974 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-06 13:11:04,665 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-06 13:11:04,671 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-06 13:11:06,139 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-06 13:11:06,144 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-06 13:11:14,328 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-06 13:11:39,191 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-06 13:11:40,389 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 58, 'pressure': 1010, 'temp': 31.99, 'weather_condition': 'Smoke', 'wind_degree': 230, 'wind_speed': 4.12}
2024-12-06 13:12:01,127 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-06 13:12:02,075 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Delhi', 'country_name': 'IN', 'humidity': 27, 'pressure': 1012, 'temp': 23.05, 'weather_condition': 'Haze', 'wind_degree': 290, 'wind_speed': 3.6}
2024-12-06 13:12:02,344 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-06 13:12:04,350 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-06 13:12:06,349 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-06 13:12:08,352 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-06 13:12:10,346 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-06 13:12:12,355 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-06 13:12:14,347 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-06 13:12:16,357 - FlaskAppLogger - INFO - Fetching weather data for city: Delhi
2024-12-06 14:52:24,016 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-06 14:52:24,020 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-06 14:52:25,914 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-06 15:00:53,411 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-06 15:04:29,715 - FlaskAppLogger - INFO - User Nitkarsh logged out.
2024-12-06 15:06:18,831 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-06 15:06:36,897 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
